---
# Override in /etc/ansible/group_vars/all
# or per-host in /etc/ansible/host_vars/[host]
aegir_sudoers: johndoe

# Permissions on /var/aegir/.ssh
# Some types of hacks (ex: WordPress plugin upgrades) override this to 0750/www-data
aegir_ssh_dir_permission: 0700
aegir_ssh_dir_group: aegir

# Default Drupal platform to install
aegir_platform_drupal_version: 7

# We can define an array of unix usernames that will be used to create
# mysql users. This is to make it easier to connect using Workbench over ssh.
aegir_mysql_users_ro: []
aegir_mysql_users_rw: []

# Defining SQL replication hosts will open the firewall port to that IP
aegir_mysql_replication_hosts: []

aegir_mysql_host: "127.0.0.1"
