---

# This is based on roles/sshuserkeys
- name: Generate a random password for read-only users
  set_fact:
    password_item: "{{ item }};{{ lookup('password', '/dev/null chars=ascii_letters,digits length=25') }}"
  with_items: "{{ mysql_users }}"
  register: password_results

- name: Format random password list
  set_fact:
    password_list: "{{ password_results.results | selectattr('skipped', 'undefined') | map(attribute='ansible_facts.password_item') | list }}"

- name: Format random password dict
  set_fact:
    password_dict: "{{ password_dict|default([]) + [ { 'name': item.split(';')[0], 'password': item.split(';')[1] } ] }}"
  with_items: "{{ password_list }}"

- name: Save the mysql user password in db.txt
  copy:
    content: "{{ item.password }}"
    dest: "/home/{{ item.name }}/db.txt"
    owner: "{{ item.name }}"
    mode: '0600'
  with_items:
    - "{{ password_dict }}"

- name: Create database user
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "*.*:{{ mysql_privs }}"
    state: present
    config_file: "/etc/mysql/debian.cnf"
  with_items:
    - "{{ password_dict }}"
